namespace BetterMultiplayer.Diagnostics;

// Fixed-shape facts keep trade diagnostics useful without accepting arbitrary
// player, room, or log text.
internal sealed record DiagnosticTradeFacts(
    string? Location = null,
    string? Stage = null,
    string? SessionId = null,
    string? ActorId = null,
    string? TargetId = null,
    bool? Available = null,
    bool? Connected = null,
    bool? Host = null,
    int? Attempt = null,
    int? Count = null,
    int? Revision = null,
    bool? Changed = null,
    bool? Accepted = null,
    bool? Success = null,
    bool? LocalConfirmed = null,
    bool? RemoteConfirmed = null,
    bool? ActorConfirmed = null,
    bool? TargetConfirmed = null,
    int? ActorCardCount = null,
    int? ActorRelicCount = null,
    int? ActorPotionCount = null,
    int? ActorGold = null,
    int? ActorReportedGold = null,
    int? TargetCardCount = null,
    int? TargetRelicCount = null,
    int? TargetPotionCount = null,
    int? TargetGold = null,
    int? TargetReportedGold = null,
    int? CardIndex = null,
    string? ItemId = null,
    int? UpgradeLevel = null,
    string? Reason = null,
    string? SessionStatus = null);
